# https://github.com/deviantony/docker-elk/blob/master/docker-compose.yml
version: '3'

services:
  
  vault:
    # docker run --cap-add=IPC_LOCK -d --name=dev-vault vault
    image:
      vault
    logging:
      driver: "json-file"
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${CASTLE_VAULT_ROOT_TOKEN_ID}
    networks:
      - castle
      
  elasticsearch:
    # https://stackoverflow.com/questions/41192680/update-max-map-count-for-elasticsearch-docker-container-mac-host
    # docker-machine ssh
    # sudo sysctl -w vm.max_map_count=262144
    build:
      context: docker-img-elasticsearch/
    logging:
      driver: "json-file"
    volumes:
      - ./docker-img-elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - castle

  logstash:
    build:
      context: docker-img-logstash/
    logging:
      driver: "json-file"
    volumes:
      - ./docker-img-logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./docker-img-logstash/config/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - castle
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: docker-img-kibana/
    logging:
      driver: "json-file"
    volumes:
      - ./docker-img-kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - castle
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: docker-img-filebeat/
    logging:
      driver: "json-file"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - castle
    depends_on:
      - elasticsearch

networks:

  castle:
    driver: bridge