# https://github.com/deviantony/docker-elk/blob/master/docker-compose.yml
version: '2'

services:

  elasticsearch:
    # https://stackoverflow.com/questions/41192680/update-max-map-count-for-elasticsearch-docker-container-mac-host
    # docker-machine ssh
    # sudo sysctl -w vm.max_map_count=262144
    build:
      context: docker-img-elasticsearch/
    volumes:
      - ./docker-img-elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - castle

  logstash:
    build:
      context: docker-img-logstash/
    volumes:
      - ./docker-img-logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./docker-img-logstash/config/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - castle
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: docker-img-kibana/
    volumes:
      - ./docker-img-kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - castle
    depends_on:
      - elasticsearch

networks:

  castle:
    driver: bridge